#!/usr/bin/env perl

use strict;
use warnings;
use v5.14;
use AppConfig;
use Bake;
use Bake::Parser;
use YAML qw/Dump/;

my $conf = AppConfig->new;
$conf->define('list');
$conf->define('dryrun',{DEFAULT=>0});
$conf->define('debug');
$conf->define('defaults=s',{DEFAULT=>$ENV{HOME}.'/.bakes'});
$conf->define('filename|default-file=s',{DEFAULT=>'bakes'});
$conf->file($ENV{HOME}.'/.bakerc');
$conf->getopt();

my $cmd = shift @ARGV;

unless (&process_bakes($conf->filename,$cmd)) {
    if (-e $conf->defaults && -r $conf->defaults) {
        &process_bakes($conf->defaults,$cmd);
    }
    else {
        say 'No valid file named "'.$conf->filename.'" found';
    }
}

exit;

sub process_bakes {
    my $file = shift;
    my $cmd = shift // undef;
    my $par = Bake::Parser->new();
    my $ret = 0;
    if (-e $file && -r $file) {
        open (FILE, $file) or die "Can't read $!\n";
        my $inst = $par->parse(join('',<FILE>));
        say Dump($inst) if $conf->debug;
        close(FILE);
        $inst->dryrun($conf->dryrun) if $conf->dryrun;
        $ret = 1;
        $inst->run($cmd,@ARGV);
    }
    return $ret;
}
